- name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest
  notify:
    - nginx systemd

- name: Install nano
  apt:
    name=nano
    state=latest

- name: Install ftp-server
  apt:
    name=proftpd
    state=latest
  notify:
    - proftpd systemd
