- name: Show hostname
  debug:
     var=ansible_hostname

- name: network info
  vars:
    msg: |
       All Interface List: {{ ansible_interfaces }}
       All IP: {{ ansible_all_ipv4_addresses }}
       Gateway: {{ ansible_default_ipv4.gateway }}
       Eth0 MAC: {{ ansible_ens4.macaddress }}
  debug:
     msg: "{{ msg.split('\n') }}"

- name: HW info
  vars:
    msg: |
       CPU: {{ ansible_processor }}
       CPU Core: {{ ansible_processor_cores }}
       RAM: {{ ansible_memtotal_mb }}
       SWAP: {{ ansible_memory_mb.swap.total }}
  debug:
     msg: "{{ msg.split('\n') }}"

- name: GCP info
  vars:
    msg: |
        Cloud: {{ ansible_product_name }}
        Serial: {{ ansible_product_serial }}
        UUID: {{ ansible_product_uuid }}
  debug:
      msg: "{{ msg.split('\n') }}"
